# Generated by Django 6.0.7 on 2026-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-priority", "deadline"]},
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
